USE MASTER
GO

IF EXISTS (SELECT * FROM sysdatabases WHERE (name = 'EFECTY')) 
BEGIN
	DROP DATABASE EFECTY
END
GO

CREATE DATABASE EFECTY
GO

USE EFECTY
GO

CREATE TABLE TIPO_DOCUMENTO
(
	ID INT IDENTITY(1,1),
	DESCRIPCION VARCHAR(50),
	CONSTRAINT PK_Tipo_Documento PRIMARY KEY(ID)
)
GO

CREATE TABLE ESTADO_CIVIL
(
	ID INT IDENTITY(1,1),
	DESCRIPCION VARCHAR(50)
	CONSTRAINT PK_Estado_civil PRIMARY KEY(ID)
)
GO

INSERT INTO TIPO_DOCUMENTO
VALUES ('Cédula de ciudadania'),
	   ('Tarjeta de identidad'),
	   ('Pasaporte')
GO

INSERT INTO ESTADO_CIVIL
VALUES ('Soltero'),
	   ('Casado'),
	   ('Divorciado')
GO

CREATE TABLE PERSONA
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRES VARCHAR(250) NOT NULL,
	APELLIDOS VARCHAR(250) NOT NULL,
	IDTIPODOCUMENTO INT NOT NULL,
	FECHANACIMIENTO DATE NOT NULL,
	VALORAGANAR NUMERIC(20,2) NOT NULL,
	IDESTADOCIVIL INT NOT NULL,
	CONSTRAINT FK_ID_TIPO_DOC FOREIGN KEY(IDTIPODOCUMENTO) REFERENCES TIPO_DOCUMENTO(ID),
	CONSTRAINT FK_ID_EST_CIVIL FOREIGN KEY(IDESTADOCIVIL) REFERENCES ESTADO_CIVIL(ID),
)
GO

/*CREAR PROCEDIMIENTOS ALMACENADOS*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF EXISTS (SELECT * FROM sys.objects WHERE NAME = 'SP_CONSULTAR_TIPOS_DOCUMENTO' AND TYPE IN ('P','SP'))
BEGIN
	DROP PROCEDURE SP_CONSULTAR_TIPOS_DOCUMENTO
END
GO
CREATE PROCEDURE [dbo].[SP_CONSULTAR_TIPOS_DOCUMENTO]
AS
BEGIN
	SET NOCOUNT ON;
	SELECT ID,DESCRIPCION FROM TIPO_DOCUMENTO;
END

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF EXISTS (SELECT * FROM sys.objects WHERE NAME = 'SP_CONSULTAR_ESTADOS_CIVIL' AND TYPE IN ('P','SP'))
BEGIN
	DROP PROCEDURE SP_CONSULTAR_ESTADOS_CIVIL
END
GO
CREATE PROCEDURE [dbo].[SP_CONSULTAR_ESTADOS_CIVIL]
AS
BEGIN
	SET NOCOUNT ON;
	SELECT ID,DESCRIPCION FROM ESTADO_CIVIL;
END

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF EXISTS (SELECT * FROM sys.objects WHERE NAME = 'SP_CREAR_PERSONA' AND TYPE IN ('P','SP'))
BEGIN
	DROP PROCEDURE SP_CREAR_PERSONA
END
GO
CREATE PROCEDURE [dbo].[SP_CREAR_PERSONA](
	@NOMBRES VARCHAR(250),
	@APELLIDOS VARCHAR(250),
	@IDTIPODOCUMENTO INT,
	@FECHANACIMIENTO DATE,
	@VALORAGANAR NUMERIC(20,2),
	@IDESTADOCIVIL INT
)
AS
BEGIN
	SET NOCOUNT ON;
	
	INSERT INTO PERSONA (NOMBRES,APELLIDOS,IDTIPODOCUMENTO,FECHANACIMIENTO,VALORAGANAR,IDESTADOCIVIL)
	VALUES(@NOMBRES,@APELLIDOS,@IDTIPODOCUMENTO,@FECHANACIMIENTO,@VALORAGANAR,@IDESTADOCIVIL)
END

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF EXISTS (SELECT * FROM sys.objects WHERE NAME = 'SP_CONSULTAR_PERSONA' AND TYPE IN ('P','SP'))
BEGIN
	DROP PROCEDURE SP_CONSULTAR_PERSONA
END
GO
CREATE PROCEDURE [dbo].[SP_CONSULTAR_PERSONA](
	@NOMBRES VARCHAR(250)
)
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT A.ID,NOMBRES,APELLIDOS,IDTIPODOCUMENTO,B.DESCRIPCION AS TIPODOCUMENTO,IDESTADOCIVIL,C.DESCRIPCION AS ESTADOCIVIL, FECHANACIMIENTO, VALORAGANAR
	FROM PERSONA A
	INNER JOIN TIPO_DOCUMENTO B ON A.IDTIPODOCUMENTO = B.ID
	INNER JOIN ESTADO_CIVIL C ON A.IDESTADOCIVIL = C.ID
	WHERE NOMBRES LIKE '%'+@NOMBRES+'%' OR @NOMBRES = ''
END
GO


/**/
EXEC SP_CONSULTAR_TIPOS_DOCUMENTO
GO
EXEC SP_CONSULTAR_ESTADOS_CIVIL
GO
EXEC SP_CREAR_PERSONA 'Jaime Andres','Fandino Herrera','1','1993-09-14','1000000','1'
GO
EXEC SP_CONSULTAR_PERSONA ''
GO